FIGURE_STYLES = {'figure_4': {'title': '',
	              'series': {'without_network': {'color': 'black',
	                                             'marker': 'o',
	                                             'show_marker': True,
	                                             'show_line': False,
	                                             'marker_fill': False,
	                                             's': 14,
                                             'label': 'Without CE-branch network',
                                             'title': '',
                                             'linestyle': 'None',
                                             'linewidth': 1.0},
	                         'r_1k': {'color': 'red',
	                                  'marker': 's',
	                                  'show_marker': True,
	                                  'show_line': False,
	                                  'marker_fill': False,
	                                  's': 14,
                                  'label': '1$\\;k\\Omega$',
                                  'title': '',
                                  'linestyle': 'None',
                                  'linewidth': 1.0},
	                         'r_1k_c_1uf': {'color': 'purple',
	                                        'marker': '^',
	                                        'show_marker': True,
	                                        'show_line': False,
	                                        'marker_fill': False,
	                                        's': 14,
                                        'label': '1$\\;k\\Omega$, 1$\\mu F$',
                                        'title': '',
                                        'linestyle': 'None',
                                        'linewidth': 1.0},
	                         'r_3k': {'color': 'darkorange',
	                                  'marker': 'v',
	                                  'show_marker': True,
	                                  'show_line': False,
	                                  'marker_fill': False,
	                                  's': 14,
                                  'label': '3$\\;k\\Omega$',
                                  'title': '',
                                  'linestyle': 'None',
                                  'linewidth': 1.0},
	                         'r_3k_c_1uf': {'color': 'green',
	                                        'marker': 'D',
	                                        'show_marker': True,
	                                        'show_line': False,
	                                        'marker_fill': False,
	                                        's': 14,
                                        'label': '3$\\;k\\Omega$, 1$\\mu F$',
                                        'title': '',
                                        'linestyle': 'None',
                                        'linewidth': 1.0},
	                         'r_10k': {'color': 'gold',
	                                   'marker': 'P',
	                                   'show_marker': True,
	                                   'show_line': False,
	                                   'marker_fill': False,
	                                   's': 14,
                                   'label': '10$\\;k\\Omega$',
                                   'title': '',
                                   'linestyle': 'None',
                                   'linewidth': 1.0},
	                         'r_10k_c_1uf': {'color': 'springgreen',
	                                         'marker': 'X',
	                                         'show_marker': True,
	                                         'show_line': False,
	                                         'marker_fill': False,
	                                         's': 14,
                                         'label': '10$\\;k\\Omega$, 1$\\mu F$',
                                         'title': '',
                                         'linestyle': 'None',
                                         'linewidth': 1.0},
	                         'r_47k': {'color': 'blue',
	                                   'marker': '*',
	                                   'show_marker': True,
	                                   'show_line': False,
	                                   'marker_fill': False,
	                                   's': 14,
                                   'label': '47$\\;k\\Omega$',
                                   'title': '',
                                   'linestyle': 'None',
                                   'linewidth': 1.0}},
	              'model': {'color': 'black',
	                        'show_marker': False,
	                        'show_line': True,
	                        'linestyle': '-',
                        'linewidth': 1.0,
                        'label': 'Dummy-cell model'},
              'legend': {'show': True, 'kwargs': {'frameon': False}}},
 'figure_5': {'title': '(a) Nyquist',
              'panel_box_aspect': 0.65,
              'bode': {'title': '(b) Bode',
                       'x_limits': (1, 1000000.0),
                       'dummy_resonance': {'show': False,
                                           'series_resistance_ohm': 100.0,
                                           'parallel_resistance_ohm': 1000.0,
                                           'capacitance_f': 1e-06,
                                           'color': 'black',
                                           'linestyle': ':',
                                           'linewidth': 1.2,
                                           'label': '$f_{\\mathrm{dummy}}$',
                                           'annotate': True,
                                           'annotation': '$f_{\\mathrm{dummy}}$'},
                       'legend': {'show': False, 'kwargs': {'fontsize': 9, 'frameon': False}}},
		              'series': {'configuration_2': {'color': 'black',
		                                             'marker': 'o',
		                                             'show_marker': True,
		                                             'show_line': False,
		                                             'marker_fill': False,
	                                             's': 20,
                                             'label': 'Configuration 2',
                                             'linestyle': 'None',
                                             'linewidth': 1.0},
	                         'c_eq_points': {'color': 'black',
	                                         'marker': '.',
	                                         'show_marker': False,
	                                         'show_line': False,
	                                         'marker_fill': True,
	                                         's': 20,
                                         'label': None,
                                         'linestyle': 'None',
                                         'linewidth': 1.0},
	                         'c_eq_line': {'color': 'black',
	                                       'show_marker': False,
	                                       'show_line': True,
	                                       'linestyle': '-',
	                                       'linewidth': 2,
                                       'label': '$C_{eq}$'}},
              'legend': {'show': True,
                         'kwargs': {'fontsize': 9,
                                    'framealpha': 0.5,
                                    'labelspacing': 0.3,
                                    'frameon': False}}},
 'figure_6': {'title': '(a) Nyquist',
              'panel_box_aspect': 0.65,
              'bode': {'title': '(b) Bode',
                       'x_limits': (1, 1000000.0),
                       'dummy_resonance': {'show': False,
                                           'series_resistance_ohm': 100.0,
                                           'parallel_resistance_ohm': 1000.0,
                                           'capacitance_f': 1e-06,
                                           'color': 'black',
                                           'linestyle': ':',
                                           'linewidth': 1.2,
                                           'label': '$f_{\\mathrm{dummy}}$',
                                           'annotate': True,
                                           'annotation': '$f_{\\mathrm{dummy}}$'},
                       'legend': {'show': False, 'kwargs': {'fontsize': 9, 'frameon': False}}},
		              'series': {'configuration_1': {'color': 'black',  # previous: 'green'
		                                             'marker': '^',  # previous: 'o'
		                                             'show_marker': True,
		                                             'show_line': False,
		                                             'marker_fill': False,
	                                             's': 20,
                                             'label': 'Configuration 1',
                                             'linestyle': 'None',
                                             'linewidth': 1.0},
		                         'configuration_3': {'color': 'k',  # previous: 'red'
		                                             'marker': 'v',  # previous: 'x'
		                                             'show_marker': True,
		                                             'show_line': False,
		                                             'marker_fill': True,
	                                             's': 12,
                                             'label': 'Configuration 3',
                                             'linestyle': 'None',
                                             'linewidth': 1.0}},
              'legend': {'show': True, 'kwargs': {'fontsize': 9, 'frameon': False}}},
 'figure_7': {'title': '(a) Nyquist',
              'panel_box_aspect': 0.65,
              'bode': {'title': '(b) Bode',
                       'x_limits': (1, 1000000.0),
                       'dummy_resonance': {'show': True,
                                           'series_resistance_ohm': 100.0,
                                           'parallel_resistance_ohm': 1000.0,
                                           'capacitance_f': 1e-06,
                                           'color': 'black',
                                           'linestyle': ':',
                                           'linewidth': 1.2,
                                           'label': '$f_{\\mathrm{dummy}}$',
                                           'annotate': True,
                                           'annotation': '$f_{\\mathrm{dummy}}$'},
                       'legend': {'show': False, 'kwargs': {'fontsize': 9, 'frameon': False}}},
		              'series': {'configuration_3_dummy': {'color': 'black',
		                                                   'marker': 'o',
		                                                   'show_marker': True,
		                                                   'show_line': False,
		                                                   'marker_fill': False,
	                                                   's': 20,
                                                   'label': 'Configuration 3 + dummy on CE',
                                                   'linestyle': 'None',
                                                   'linewidth': 1.0},
		                         'configuration_3': {'color': 'k',  # previous: 'red'
		                                             'marker': 'v',  # previous: 'x'
		                                             'show_marker': True,
		                                             'show_line': False,
		                                             'marker_fill': True,
	                                             's': 12,
                                             'label': 'Configuration 3',
                                             'linestyle': 'None',
                                             'linewidth': 1.0},
			                         'configuration_2_dummy': {'color': 'black',
			                                                   'marker': '+',
			                                                   'show_marker': True,
			                                                   'show_line': False,
			                                                   'marker_fill': False,
		                                                   's': 15,
	                                                   'label': 'Configuration 2 + dummy on CE',
		                                                   'linestyle': 'None',
		                                                   'linewidth': 1.0},
			                         'configuration_1_pt_ce': {'show': False,
			                                                   'color': 'black',  # previous: 'green'
			                                                   'marker': '^',  # previous: 'o'
			                                                   'show_marker': True,
			                                                   'show_line': False,
			                                                   'marker_fill': False,
			                                                   's': 12,
			                                                   'label': 'Configuration 1',
			                                                   'linestyle': 'None',
			                                                   'linewidth': 1.0}},
              'legend': {'show': True, 'kwargs': {'fontsize': 9, 'frameon': False}}},
 'supplementary_pair': {'title': '(a) Nyquist',
                        'panel_box_aspect': 0.65,
                        'bode': {'title': '(b) Bode',
                                 'x_limits': (0.1, 1000000.0),
                                 'dummy_resonance': {'show': False,
                                                     'series_resistance_ohm': 100.0,
                                           'parallel_resistance_ohm': 1000.0,
                                                     'capacitance_f': 1e-06,
                                                     'color': 'black',
                                                     'linestyle': ':',
                                                     'linewidth': 1.2,
                                                     'label': '$f_{\\mathrm{dummy}}$',
                                                     'annotate': True,
                                                     'annotation': '$f_{\\mathrm{dummy}}$'},
                                 'legend': {'show': False, 'kwargs': {'frameon': False}}},
		                        'series': {'configuration_1': {'color': 'black',  # previous: 'green'
		                                                       'marker': '^',  # previous: 'o'
		                                                       'show_marker': True,
		                                                       'show_line': False,
		                                                       'marker_fill': False,
	                                                       's': 20,
                                                       'label': 'Configuration 1',
                                                       'linestyle': 'None',
                                                       'linewidth': 1.0},
		                                   'configuration_3': {'color': 'black',  # previous: 'red'
		                                                       'marker': 'v',  # previous: 'x'
		                                                       'show_marker': True,
		                                                       'show_line': False,
		                                                       'marker_fill': True,
	                                                       's': 14,
                                                       'label': 'Configuration 3',
                                                       'linestyle': 'None',
                                                       'linewidth': 1.0}},
                        'legend': {'show': True, 'kwargs': {'frameon': False}}}}
